; generated by Slic3r 0.9.10b on 2013-11-21 at 13:33:23

; layer_height = 0.2
; perimeters = 3
; top_solid_layers = 3
; bottom_solid_layers = 3
; fill_density = 0.4
; perimeter_speed = 30
; infill_speed = 60
; travel_speed = 130
; nozzle_diameter = 0.5
; filament_diameter = 3
; extrusion_multiplier = 1
; perimeters extrusion width = 0.85mm
; infill extrusion width = 1.02mm
; solid infill extrusion width = 0.85mm
; top infill extrusion width = 0.85mm
; first layer extrusion width = 0.40mm

G21 ; set units to millimeters
M107
M104 S200 ; set temperature
G28 ; home all axes
G1 Z5 F5000 ; lift nozzle

M109 S200 ; wait for temperature to be reached
G90 ; use absolute coordinates
G92 E0
M82 ; use absolute distances for extrusion
G1 F1800.000 E-1.00000
G92 E0
G1 Z0.200 F7800.000
G1 X100 Y100
G1 F600 E1.00000
G1 X110 Y100 E0.1192
G1 X105 Y95
G1 X105 Y105 E0.2385


M107
M104 S0 ; turn off temperature
G28 X0  ; home X axis
M84     ; disable motors


